/**
 * API 에러 코드 정의
 *
 * @description
 * - 일관된 에러 코드 사용
 * - 프론트엔드와 에러 코드 공유
 */
export const ERROR_CODES = {
  // 인증 & 권한 (AUTH)
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_CREDENTIALS_INVALID: 'AUTH_CREDENTIALS_INVALID',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_VERIFICATION_FAILED: 'TOKEN_VERIFICATION_FAILED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  NICKNAME_ALREADY_EXISTS: 'NICKNAME_ALREADY_EXISTS',
  MEMBER_PENDING: 'MEMBER_PENDING',
  MEMBER_WITHDRAWN: 'MEMBER_WITHDRAWN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // 회원 (MEMBER)
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_ALREADY_EXISTS: 'MEMBER_ALREADY_EXISTS',
  MEMBER_EMAIL_EXISTS: 'MEMBER_EMAIL_EXISTS',
  MEMBER_NICKNAME_EXISTS: 'MEMBER_NICKNAME_EXISTS',
  MEMBER_SUSPENDED: 'MEMBER_SUSPENDED',
  MEMBER_BANNED: 'MEMBER_BANNED',
  MEMBER_PENDING_APPROVAL: 'MEMBER_PENDING_APPROVAL',
  MEMBER_ALREADY_WITHDRAWN: 'MEMBER_ALREADY_WITHDRAWN',
  MEMBER_NOT_PENDING: 'MEMBER_NOT_PENDING',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',

  // 게시글 (POST)
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_ALREADY_DELETED: 'POST_ALREADY_DELETED',
  POST_ACCESS_DENIED: 'POST_ACCESS_DENIED',

  // 댓글 (COMMENT)
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_ALREADY_DELETED: 'COMMENT_ALREADY_DELETED',
  COMMENT_ACCESS_DENIED: 'COMMENT_ACCESS_DENIED',

  // 투표 (VOTE)
  VOTE_NOT_FOUND: 'VOTE_NOT_FOUND',
  VOTE_ALREADY_CLOSED: 'VOTE_ALREADY_CLOSED',
  VOTE_ALREADY_PARTICIPATED: 'VOTE_ALREADY_PARTICIPATED',
  VOTE_NOT_STARTED: 'VOTE_NOT_STARTED',

  // 신고 (REPORT)
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  REPORT_ALREADY_PROCESSED: 'REPORT_ALREADY_PROCESSED',
  REPORT_SELF_NOT_ALLOWED: 'REPORT_SELF_NOT_ALLOWED',

  // 불편/제안 (SUGGESTION)
  SUGGESTION_NOT_FOUND: 'SUGGESTION_NOT_FOUND',
  SUGGESTION_ALREADY_PROCESSED: 'SUGGESTION_ALREADY_PROCESSED',

  // 검증 (VALIDATION)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',

  // 데이터베이스 (DATABASE)
  DATABASE_ERROR: 'DATABASE_ERROR',
  DUPLICATE_ERROR: 'DUPLICATE_ERROR',
  NOT_FOUND: 'NOT_FOUND',

  // 서버 (SERVER)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  BAD_REQUEST: 'BAD_REQUEST',

  // 파일 (FILE)
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
} as const;

/**
 * 에러 코드 타입
 */
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * 에러 메시지 매핑
 */
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  // 인증 & 권한
  AUTH_UNAUTHORIZED: '인증이 필요합니다.',
  AUTH_FORBIDDEN: '접근 권한이 없습니다.',
  AUTH_TOKEN_EXPIRED: '토큰이 만료되었습니다.',
  AUTH_TOKEN_INVALID: '유효하지 않은 토큰입니다.',
  AUTH_CREDENTIALS_INVALID: '이메일 또는 비밀번호가 올바르지 않습니다.',
  TOKEN_MISSING: '인증 토큰이 제공되지 않았습니다.',
  TOKEN_EXPIRED: '토큰이 만료되었습니다.',
  TOKEN_INVALID: '유효하지 않은 토큰입니다.',
  TOKEN_VERIFICATION_FAILED: '토큰 검증에 실패했습니다.',
  REFRESH_TOKEN_EXPIRED: 'Refresh Token이 만료되었습니다.',
  REFRESH_TOKEN_INVALID: 'Refresh Token이 유효하지 않습니다.',
  INVALID_CREDENTIALS: '이메일 또는 비밀번호가 올바르지 않습니다.',
  INVALID_PASSWORD: '비밀번호가 올바르지 않습니다.',
  WEAK_PASSWORD: '너무 약한 비밀번호입니다.',
  EMAIL_ALREADY_EXISTS: '이미 사용 중인 이메일입니다.',
  NICKNAME_ALREADY_EXISTS: '이미 사용 중인 닉네임입니다.',
  MEMBER_PENDING: '승인 대기 중인 회원입니다.',
  MEMBER_WITHDRAWN: '탈퇴한 회원입니다.',
  UNAUTHORIZED: '인증이 필요합니다.',
  FORBIDDEN: '접근 권한이 없습니다.',

  // 회원
  MEMBER_NOT_FOUND: '회원을 찾을 수 없습니다.',
  MEMBER_ALREADY_EXISTS: '이미 가입된 회원입니다.',
  MEMBER_EMAIL_EXISTS: '이미 사용 중인 이메일입니다.',
  MEMBER_NICKNAME_EXISTS: '이미 사용 중인 닉네임입니다.',
  MEMBER_SUSPENDED: '정지된 계정입니다.',
  MEMBER_BANNED: '강퇴된 계정입니다.',
  MEMBER_PENDING_APPROVAL: '승인 대기 중인 계정입니다.',
  MEMBER_ALREADY_WITHDRAWN: '이미 탈퇴한 회원입니다.',
  MEMBER_NOT_PENDING: '승인 대기 중인 회원이 아닙니다.',
  INVALID_STATUS_TRANSITION: '유효하지 않은 상태 전환입니다.',

  // 게시글
  POST_NOT_FOUND: '게시글을 찾을 수 없습니다.',
  POST_ALREADY_DELETED: '이미 삭제된 게시글입니다.',
  POST_ACCESS_DENIED: '게시글에 접근할 권한이 없습니다.',

  // 댓글
  COMMENT_NOT_FOUND: '댓글을 찾을 수 없습니다.',
  COMMENT_ALREADY_DELETED: '이미 삭제된 댓글입니다.',
  COMMENT_ACCESS_DENIED: '댓글에 접근할 권한이 없습니다.',

  // 투표
  VOTE_NOT_FOUND: '투표를 찾을 수 없습니다.',
  VOTE_ALREADY_CLOSED: '이미 마감된 투표입니다.',
  VOTE_ALREADY_PARTICIPATED: '이미 참여한 투표입니다.',
  VOTE_NOT_STARTED: '아직 시작하지 않은 투표입니다.',

  // 신고
  REPORT_NOT_FOUND: '신고 내역을 찾을 수 없습니다.',
  REPORT_ALREADY_PROCESSED: '이미 처리된 신고입니다.',
  REPORT_SELF_NOT_ALLOWED: '자신의 게시물은 신고할 수 없습니다.',

  // 불편/제안
  SUGGESTION_NOT_FOUND: '불편/제안을 찾을 수 없습니다.',
  SUGGESTION_ALREADY_PROCESSED: '이미 처리된 불편/제안입니다.',

  // 검증
  VALIDATION_ERROR: '입력값 검증에 실패했습니다.',
  VALIDATION_REQUIRED_FIELD: '필수 항목이 누락되었습니다.',
  VALIDATION_INVALID_FORMAT: '올바르지 않은 형식입니다.',

  // 데이터베이스
  DATABASE_ERROR: '데이터베이스 오류가 발생했습니다.',
  DUPLICATE_ERROR: '이미 존재하는 데이터입니다.',
  NOT_FOUND: '요청한 데이터를 찾을 수 없습니다.',

  // 서버
  INTERNAL_SERVER_ERROR: '서버 오류가 발생했습니다.',
  SERVICE_UNAVAILABLE: '서비스를 일시적으로 사용할 수 없습니다.',
  BAD_REQUEST: '잘못된 요청입니다.',

  // 파일
  FILE_TOO_LARGE: '파일 크기가 너무 큽니다.',
  FILE_INVALID_TYPE: '지원하지 않는 파일 형식입니다.',
  FILE_UPLOAD_FAILED: '파일 업로드에 실패했습니다.',
};
